{% set name = "resdk" %}
{% set version = "21.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/resdk-{{ version }}.tar.gz
  sha256: 5b231e655674f0362e72846bbf66e36afe82f595acbca32dbc77656517c21f2e

build:
  skip: true  # [py>=313]
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=64.0.0
    - setuptools-scm >=6.4.0
    - pip
  run:
    - python
    - aiohttp >=3.9.3,<3.10.dev0
    - requests >=2.6.0
    - urllib3 >=2  # [py>=310]
    - slumber >=0.7.1
    - wrapt
    - pytz >=2018.4
    - tzlocal >=1.5.1
    - pandas >=1.0.0
    - tqdm
    - openpyxl
    - xlrd
    - boto3
    - boto3
       #- botocore >=1.34,<2.dev0   [py>=310]
      #relies on https://github.com/conda-forge/botocore-feedstock/blob/arch-specific/recipe/meta.yaml
    - packaging
        #- mypy-boto3-s3 not listed in toml file, but required at testing
test:
  imports:
    - resdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/genialis/resolwe-bio-py
  summary: Resolwe SDK for Python
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Resolwe SDK for Python supports interaction with Resolwe server and its extension Resolwe Bioinformatics. You can use it to upload and inspect biomedical data sets, contribute annotations, run analysis, and write pipelines.
  doc_url: https://resdk.readthedocs.io/en/latest/
  dev_url: https://github.com/genialis/resolwe-bio-py

extra:
  recipe-maintainers:
    - HeavyTony2
