schema_version: 1

context:
  name: resdk
  version: "22.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/resdk-${{ version }}.tar.gz
  sha256: 6f733082e1cfe7612f75b4bb23185eeff75877144ed880227fe22688318ae387

build:
  number: 0
  #skip: match(python, ">=3.15")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
   #build:
    #- if: build_platform != target_platform
      #then:
        #- python
        #- cross-python_${{ target_platform }}
  host:
    - python ${{ python_min }}*
    - setuptools >=80.9.0
    - setuptools-scm >=9.2.2
    - pip
  run:
    - python >=${{ python_min }},<3.15
    - aiohttp >=3.13.2
    - requests
    #- if: match(python, ">=3.10")
      #then: urllib3 >=2
    - urllib3 >=2
    - slumber >=0.7.1
    - wrapt
    - pytz
    - tzlocal
    - pandas <3.0.0
    - tqdm
    - openpyxl
    - xlrd
    - boto3
    - boto3-stubs
    - packaging
    - botocore
    - mypy-boto3-s3  #not listed in toml file, but required at testing

tests:
  - python:
      imports:
        - resdk
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Resolwe SDK for Python
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Resolwe SDK for Python supports interaction with Resolwe server and its extension Resolwe Bioinformatics. You can use it to upload and inspect biomedical data sets, contribute annotations, run analysis, and write pipelines.
  homepage: https://github.com/genialis/resolwe-bio-py
  repository: https://github.com/genialis/resolwe-bio-py
  documentation: https://resdk.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - HeavyTony2
